// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"strings"
)

const getChatHistory = `-- name: GetChatHistory :many
SELECT chat_id, steam_id, name, message, team_only, created_on FROM chat_history
WHERE steam_id = ?
`

func (q *Queries) GetChatHistory(ctx context.Context, steamID int64) ([]ChatHistory, error) {
	rows, err := q.db.QueryContext(ctx, getChatHistory, steamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatHistory
	for rows.Next() {
		var i ChatHistory
		if err := rows.Scan(
			&i.ChatID,
			&i.SteamID,
			&i.Name,
			&i.Message,
			&i.TeamOnly,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotes = `-- name: GetNotes :many
SELECT steam_id, note, updated_on FROM notes
WHERE steam_id IN (/*SLICE:steam_ids*/?)
`

func (q *Queries) GetNotes(ctx context.Context, steamIds []int64) ([]Note, error) {
	query := getNotes
	var queryParams []interface{}
	if len(steamIds) > 0 {
		for _, v := range steamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:steam_ids*/?", strings.Repeat(",?", len(steamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:steam_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.SteamID, &i.Note, &i.UpdatedOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChat = `-- name: InsertChat :exec
INSERT INTO chat_history (chat_id, steam_id, name, message, team_only, created_on)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertChatParams struct {
	ChatID    int64
	SteamID   int64
	Name      string
	Message   string
	TeamOnly  int64
	CreatedOn int64
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) error {
	_, err := q.db.ExecContext(ctx, insertChat,
		arg.ChatID,
		arg.SteamID,
		arg.Name,
		arg.Message,
		arg.TeamOnly,
		arg.CreatedOn,
	)
	return err
}

const insertMark = `-- name: InsertMark :exec
INSERT INTO marks (steam_id, tag, note, created_on, updated_on)
VALUES (?, ?, ?, ?, ?)
`

type InsertMarkParams struct {
	SteamID   int64
	Tag       string
	Note      string
	CreatedOn int64
	UpdatedOn int64
}

func (q *Queries) InsertMark(ctx context.Context, arg InsertMarkParams) error {
	_, err := q.db.ExecContext(ctx, insertMark,
		arg.SteamID,
		arg.Tag,
		arg.Note,
		arg.CreatedOn,
		arg.UpdatedOn,
	)
	return err
}

const insertNote = `-- name: InsertNote :exec
INSERT INTO notes (steam_id, note, updated_on) VALUES (?, ?, ?)
`

type InsertNoteParams struct {
	SteamID   int64
	Note      string
	UpdatedOn int64
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, insertNote, arg.SteamID, arg.Note, arg.UpdatedOn)
	return err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes SET note = ?,  updated_on = ? WHERE steam_id = ?
`

type UpdateNoteParams struct {
	Note      string
	UpdatedOn int64
	SteamID   int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateNote, arg.Note, arg.UpdatedOn, arg.SteamID)
	return err
}
