// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.9.0
// 	protoc               v6.31.1
// source: plugins.proto

package plugins

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EvtKill       EventType = 0
	EventType_EvtMsg        EventType = 1
	EventType_EvtConnect    EventType = 2
	EventType_EvtDisconnect EventType = 3
	EventType_EvtStatusID   EventType = 4
	EventType_EvtHostname   EventType = 5
	EventType_EvtMap        EventType = 6
	EventType_EvtTags       EventType = 7
	EventType_EvtAddress    EventType = 8
	EventType_EvtLobby      EventType = 9
	EventType_EvtAny        EventType = -1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EvtKill",
		1:  "EvtMsg",
		2:  "EvtConnect",
		3:  "EvtDisconnect",
		4:  "EvtStatusID",
		5:  "EvtHostname",
		6:  "EvtMap",
		7:  "EvtTags",
		8:  "EvtAddress",
		9:  "EvtLobby",
		-1: "EvtAny",
	}
	EventType_value = map[string]int32{
		"EvtKill":       0,
		"EvtMsg":        1,
		"EvtConnect":    2,
		"EvtDisconnect": 3,
		"EvtStatusID":   4,
		"EvtHostname":   5,
		"EvtMap":        6,
		"EvtTags":       7,
		"EvtAddress":    8,
		"EvtLobby":      9,
		"EvtAny":        -1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

type Team int32

const (
	Team_UNASSIGNED Team = 0
	Team_SPEC       Team = 1
	Team_BLU        Team = 2
	Team_RED        Team = 3
)

// Enum value maps for Team.
var (
	Team_name = map[int32]string{
		0: "UNASSIGNED",
		1: "SPEC",
		2: "BLU",
		3: "RED",
	}
	Team_value = map[string]int32{
		"UNASSIGNED": 0,
		"SPEC":       1,
		"BLU":        2,
		"RED":        3,
	}
)

func (x Team) Enum() *Team {
	p := new(Team)
	*p = x
	return p
}

type LogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ErrorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=tftui.EventType" json:"Type,omitempty"`
	Player          string    `protobuf:"bytes,2,opt,name=Player,proto3" json:"Player,omitempty"`
	PlayerSID       uint64    `protobuf:"varint,3,opt,name=PlayerSID,proto3" json:"PlayerSID,omitempty"`
	PlayerPing      uint32    `protobuf:"varint,4,opt,name=PlayerPing,proto3" json:"PlayerPing,omitempty"`
	PlayerConnected uint32    `protobuf:"varint,5,opt,name=PlayerConnected,proto3" json:"PlayerConnected,omitempty"`
	Team            Team      `protobuf:"varint,6,opt,name=Team,proto3,enum=tftui.Team" json:"Team,omitempty"`
	UserID          uint32    `protobuf:"varint,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Victim          string    `protobuf:"bytes,8,opt,name=Victim,proto3" json:"Victim,omitempty"`
	VictimSID       uint64    `protobuf:"varint,9,opt,name=VictimSID,proto3" json:"VictimSID,omitempty"`
	Message         string    `protobuf:"bytes,10,opt,name=Message,proto3" json:"Message,omitempty"`
	Timestamp       uint64    `protobuf:"varint,11,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	MetaData        string    `protobuf:"bytes,12,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	Dead            bool      `protobuf:"varint,13,opt,name=Dead,proto3" json:"Dead,omitempty"`
	Raw             string    `protobuf:"bytes,14,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LogEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EvtKill
}

func (x *LogEvent) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *LogEvent) GetPlayerSID() uint64 {
	if x != nil {
		return x.PlayerSID
	}
	return 0
}

func (x *LogEvent) GetPlayerPing() uint32 {
	if x != nil {
		return x.PlayerPing
	}
	return 0
}

func (x *LogEvent) GetPlayerConnected() uint32 {
	if x != nil {
		return x.PlayerConnected
	}
	return 0
}

func (x *LogEvent) GetTeam() Team {
	if x != nil {
		return x.Team
	}
	return Team_UNASSIGNED
}

func (x *LogEvent) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LogEvent) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

func (x *LogEvent) GetVictimSID() uint64 {
	if x != nil {
		return x.VictimSID
	}
	return 0
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEvent) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *LogEvent) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *LogEvent) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type LogEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool      `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Modified bool      `protobuf:"varint,2,opt,name=Modified,proto3" json:"Modified,omitempty"`
	Message  string    `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	LogEvent *LogEvent `protobuf:"bytes,4,opt,name=LogEvent,proto3" json:"LogEvent,omitempty"`
}

func (x *LogEventResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LogEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogEventResponse) GetModified() bool {
	if x != nil {
		return x.Modified
	}
	return false
}

func (x *LogEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEventResponse) GetLogEvent() *LogEvent {
	if x != nil {
		return x.LogEvent
	}
	return nil
}

// The host functions embedded into the plugin
// go:plugin type=host
type LoggingFunctions interface {
	// Debug log
	Debug(context.Context, *LogMessage) (*emptypb.Empty, error)
	// Info log
	Info(context.Context, *LogMessage) (*emptypb.Empty, error)
	// Warn log
	Warn(context.Context, *LogMessage) (*emptypb.Empty, error)
	// Error log
	Error(context.Context, *LogMessage) (*emptypb.Empty, error)
}

// The greeting service definition.
// go:plugin type=plugin version=1
type LogEvents interface {
	// Sends a greeting
	OnLogEvent(context.Context, *LogEvent) (*LogEventResponse, error)
	Unload(context.Context, *emptypb.Empty) (*ErrorResponse, error)
}
