// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: logger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggerRequest) Reset() {
	*x = LoggerRequest{}
	mi := &file_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerRequest) ProtoMessage() {}

func (x *LoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerRequest.ProtoReflect.Descriptor instead.
func (*LoggerRequest) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LoggerRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggerResponse) Reset() {
	*x = LoggerResponse{}
	mi := &file_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerResponse) ProtoMessage() {}

func (x *LoggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerResponse.ProtoReflect.Descriptor instead.
func (*LoggerResponse) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{1}
}

var File_logger_proto protoreflect.FileDescriptor

const file_logger_proto_rawDesc = "" +
	"\n" +
	"\flogger.proto\x12\x05proto\")\n" +
	"\rLoggerRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x10\n" +
	"\x0eLoggerResponse2\xdf\x01\n" +
	"\x06Logger\x124\n" +
	"\x05Info3\x12\x14.proto.LoggerRequest\x1a\x15.proto.LoggerResponse\x123\n" +
	"\x04Warn\x12\x14.proto.LoggerRequest\x1a\x15.proto.LoggerResponse\x124\n" +
	"\x05Error\x12\x14.proto.LoggerRequest\x1a\x15.proto.LoggerResponse\x124\n" +
	"\x05Debug\x12\x14.proto.LoggerRequest\x1a\x15.proto.LoggerResponseB\tZ\a./protob\x06proto3"

var (
	file_logger_proto_rawDescOnce sync.Once
	file_logger_proto_rawDescData []byte
)

func file_logger_proto_rawDescGZIP() []byte {
	file_logger_proto_rawDescOnce.Do(func() {
		file_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)))
	})
	return file_logger_proto_rawDescData
}

var file_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logger_proto_goTypes = []any{
	(*LoggerRequest)(nil),  // 0: proto.LoggerRequest
	(*LoggerResponse)(nil), // 1: proto.LoggerResponse
}
var file_logger_proto_depIdxs = []int32{
	0, // 0: proto.Logger.Info3:input_type -> proto.LoggerRequest
	0, // 1: proto.Logger.Warn:input_type -> proto.LoggerRequest
	0, // 2: proto.Logger.Error:input_type -> proto.LoggerRequest
	0, // 3: proto.Logger.Debug:input_type -> proto.LoggerRequest
	1, // 4: proto.Logger.Info3:output_type -> proto.LoggerResponse
	1, // 5: proto.Logger.Warn:output_type -> proto.LoggerResponse
	1, // 6: proto.Logger.Error:output_type -> proto.LoggerResponse
	1, // 7: proto.Logger.Debug:output_type -> proto.LoggerResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logger_proto_init() }
func file_logger_proto_init() {
	if File_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logger_proto_goTypes,
		DependencyIndexes: file_logger_proto_depIdxs,
		MessageInfos:      file_logger_proto_msgTypes,
	}.Build()
	File_logger_proto = out.File
	file_logger_proto_goTypes = nil
	file_logger_proto_depIdxs = nil
}
