// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: pkg/plugins/proto/rcon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RCONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RCONRequest) Reset() {
	*x = RCONRequest{}
	mi := &file_pkg_plugins_proto_rcon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RCONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RCONRequest) ProtoMessage() {}

func (x *RCONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_rcon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RCONRequest.ProtoReflect.Descriptor instead.
func (*RCONRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_rcon_proto_rawDescGZIP(), []int{0}
}

func (x *RCONRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RCONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RCONResponse) Reset() {
	*x = RCONResponse{}
	mi := &file_pkg_plugins_proto_rcon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RCONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RCONResponse) ProtoMessage() {}

func (x *RCONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_rcon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RCONResponse.ProtoReflect.Descriptor instead.
func (*RCONResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_rcon_proto_rawDescGZIP(), []int{1}
}

func (x *RCONResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_pkg_plugins_proto_rcon_proto protoreflect.FileDescriptor

const file_pkg_plugins_proto_rcon_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/plugins/proto/rcon.proto\x12\x05proto\"'\n" +
	"\vRCONRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"*\n" +
	"\fRCONResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2:\n" +
	"\x04RCON\x122\n" +
	"\aCommand\x12\x12.proto.RCONRequest\x1a\x13.proto.RCONResponseB\tZ\a./protob\x06proto3"

var (
	file_pkg_plugins_proto_rcon_proto_rawDescOnce sync.Once
	file_pkg_plugins_proto_rcon_proto_rawDescData []byte
)

func file_pkg_plugins_proto_rcon_proto_rawDescGZIP() []byte {
	file_pkg_plugins_proto_rcon_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_proto_rcon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_rcon_proto_rawDesc), len(file_pkg_plugins_proto_rcon_proto_rawDesc)))
	})
	return file_pkg_plugins_proto_rcon_proto_rawDescData
}

var file_pkg_plugins_proto_rcon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_plugins_proto_rcon_proto_goTypes = []any{
	(*RCONRequest)(nil),  // 0: proto.RCONRequest
	(*RCONResponse)(nil), // 1: proto.RCONResponse
}
var file_pkg_plugins_proto_rcon_proto_depIdxs = []int32{
	0, // 0: proto.RCON.Command:input_type -> proto.RCONRequest
	1, // 1: proto.RCON.Command:output_type -> proto.RCONResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_plugins_proto_rcon_proto_init() }
func file_pkg_plugins_proto_rcon_proto_init() {
	if File_pkg_plugins_proto_rcon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_rcon_proto_rawDesc), len(file_pkg_plugins_proto_rcon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_proto_rcon_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_proto_rcon_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_proto_rcon_proto_msgTypes,
	}.Build()
	File_pkg_plugins_proto_rcon_proto = out.File
	file_pkg_plugins_proto_rcon_proto_goTypes = nil
	file_pkg_plugins_proto_rcon_proto_depIdxs = nil
}
