// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/plugins/proto/rcon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RCON_Command_FullMethodName = "/proto.RCON/Command"
)

// RCONClient is the client API for RCON service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RCONClient interface {
	Command(ctx context.Context, in *RCONRequest, opts ...grpc.CallOption) (*RCONResponse, error)
}

type rCONClient struct {
	cc grpc.ClientConnInterface
}

func NewRCONClient(cc grpc.ClientConnInterface) RCONClient {
	return &rCONClient{cc}
}

func (c *rCONClient) Command(ctx context.Context, in *RCONRequest, opts ...grpc.CallOption) (*RCONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RCONResponse)
	err := c.cc.Invoke(ctx, RCON_Command_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RCONServer is the server API for RCON service.
// All implementations should embed UnimplementedRCONServer
// for forward compatibility.
type RCONServer interface {
	Command(context.Context, *RCONRequest) (*RCONResponse, error)
}

// UnimplementedRCONServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRCONServer struct{}

func (UnimplementedRCONServer) Command(context.Context, *RCONRequest) (*RCONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}
func (UnimplementedRCONServer) testEmbeddedByValue() {}

// UnsafeRCONServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RCONServer will
// result in compilation errors.
type UnsafeRCONServer interface {
	mustEmbedUnimplementedRCONServer()
}

func RegisterRCONServer(s grpc.ServiceRegistrar, srv RCONServer) {
	// If the following call pancis, it indicates UnimplementedRCONServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RCON_ServiceDesc, srv)
}

func _RCON_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RCONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCONServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCON_Command_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCONServer).Command(ctx, req.(*RCONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RCON_ServiceDesc is the grpc.ServiceDesc for RCON service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RCON_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RCON",
	HandlerType: (*RCONServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _RCON_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugins/proto/rcon.proto",
}
