// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

type ChatHistory struct {
	ChatID    int64
	MatchID   int64
	SteamID   int64
	Name      string
	Message   string
	TeamOnly  int64
	CreatedOn int64
}

type Mark struct {
	SteamID   int64
	Tags      string
	Note      string
	CreatedOn int64
	UpdatedOn int64
}

type Match struct {
	MatchID   int64
	Hostname  string
	Address   string
	Duration  int64
	CreatedOn int64
}

type MatchPlayer struct {
	MatchID   int64
	SteamID   int64
	Score     int64
	Deaths    int64
	Ping      int64
	Connected int64
}

type Note struct {
	SteamID   int64
	Note      string
	UpdatedOn int64
}

type Player struct {
	SteamID      int64
	Name         string
	KillsAgainst int64
	KilledBy     int64
	CreatedOn    int64
	UpdatedOn    int64
}
