name: Validation Workflow

on:
  push:

env:
  STEAM_API_KEY: ${{secrets.STEAM_API_KEY}}

jobs:
  lint:
    name: Linter
    environment: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        # TODO remove
        with:
          args: --disable unused

  test:
    runs-on: ubuntu-latest
    name: Test
    environment: master
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true

      - name: Test
        run: make test
